version: 2
jobs:
  build:
    docker:
      - image: windyfairy/cienv

    steps:
      - checkout

      - run:
          name: Build project
          command: make

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir -p deploy
              mv build/*.zip deploy/
              ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete "release-`date '+%Y%m%d-%H%M%S'`" deploy/
            fi
